// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeouegslomzbitdwhxrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllb3VlZ3Nsb216Yml0ZHdoeHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Mjc2OTMsImV4cCI6MjA2MDEwMzY5M30.bHSoKV0mEXc1xmwoUgIYBdVI60cWZf8bOnVw9ARL5z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);